"""Pydantic schemas — request/response shapes for the API.

Pydantic does the validation so we don't have to. If a user sends bad data
(e.g. negative cable length), FastAPI rejects the request before it hits us.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field


# --- Section ---------------------------------------------------------------

class SectionBase(BaseModel):
    district: Optional[str] = None
    cable_length_m: float = Field(..., gt=0, description="Cable length, metres")
    rated_power_kw: float = Field(..., gt=0)
    rated_current_a: float = Field(..., gt=0)
    wire_type: str = Field(..., min_length=1, max_length=50)
    installed_on: datetime
    avg_consumption_kwh: float = Field(..., ge=0)
    geometry: dict[str, Any] = Field(
        ..., description="GeoJSON LineString geometry — {'type':'LineString','coordinates':[[lon,lat],...]}"
    )


class SectionCreate(SectionBase):
    id: Optional[int] = Field(None, description="Optional external ID (else autogenerated)")


class SectionUpdate(BaseModel):
    district: Optional[str] = None
    cable_length_m: Optional[float] = Field(None, gt=0)
    rated_power_kw: Optional[float] = Field(None, gt=0)
    rated_current_a: Optional[float] = Field(None, gt=0)
    wire_type: Optional[str] = None
    installed_on: Optional[datetime] = None
    avg_consumption_kwh: Optional[float] = Field(None, ge=0)
    geometry: Optional[dict[str, Any]] = None


class SectionOut(SectionBase):
    id: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)


# --- Reading ---------------------------------------------------------------

class ReadingBase(BaseModel):
    measured_on: datetime
    coating_condition: float = Field(..., ge=0, le=10)
    sag_cm: float = Field(..., ge=0)
    axis_deviation_cm: float = Field(..., ge=0)
    vegetation_clearance_cm: float = Field(..., ge=0)
    resistance_ohm: float = Field(..., ge=0)


class ReadingCreate(ReadingBase):
    section_id: int


class ReadingOut(ReadingBase):
    pk: int
    section_id: int
    model_config = ConfigDict(from_attributes=True)


# --- Forecast --------------------------------------------------------------

class ForecastValueRequest(BaseModel):
    section_id: int
    parameter: str = Field(..., description="Reading field to forecast (e.g. resistance_ohm)")
    target_date: datetime


class ForecastValueResponse(BaseModel):
    section_id: int
    parameter: str
    target_date: datetime
    predicted_value: float
    slope: float
    intercept: float
    sample_count: int


class ForecastDateRequest(BaseModel):
    section_id: int
    parameter: str
    target_value: float


class ForecastDateResponse(BaseModel):
    section_id: int
    parameter: str
    target_value: float
    predicted_date: Optional[datetime]
    slope: float
    intercept: float
    sample_count: int


# --- Analytics responses ---------------------------------------------------

class DistrictCount(BaseModel):
    district: str
    section_count: int


class AgingSection(BaseModel):
    id: int
    installed_on: datetime
    age_years: float
    wire_type: str


class ConsumptionRow(BaseModel):
    id: int
    district: Optional[str] = None
    avg_consumption_kwh: float


# --- AI query --------------------------------------------------------------

class AIQueryRequest(BaseModel):
    question: str


class AIQueryResponse(BaseModel):
    answer: str
    matched_section_ids: List[int] = []
    interpretation: Optional[str] = None
